### ISSUE TITLE
Działanie API

### ISSUE THREAD

**Issue by Archie91pl** [b44x/filmweb-api#5]
Czy API jeszcze działa? Jakieś 2 lata temu jeszcze działało, teraz dostaję cały czas błędy i nie mogę nic pobrać.

**Comment by b44x** [comment]
Cześć, w wolnej chwili przejrzę i zweryfikuję działanie.

**Comment by xninedesign** [comment]
U mnie tak to wygląda po odpaleniu test.php

`Fatal error: Uncaught Exception: Nie otrzymano odpowiedzi in /home/HOST/websites/FWAPI/fw/Filmweb/nSolutions/Request.php:43 Stack trace: #0 /home/HOST/websites/FWAPI/fw/Filmweb/nSolutions/API/Methods.php(107): nSolutions\Request::execute(Array, Array) #1 /home/HOST/websites/FWAPI/fw/Filmweb/nSolutions/API/Methods.php(38): nSolutions\API\Methods->_process() #2 /home/HOST/websites/FWAPI/fw/tests/test.php(36): nSolutions\API\Methods->execute() #3 {main} thrown in /home/HOST/websites/FWAPI/fw/Filmweb/nSolutions/Request.php on line 43`
